//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindPrimeNumbersWithMultiThread
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prime
    {
        public int Id { get; set; }
        public int prime1 { get; set; }
    }
}
